server:
  port: 9090
spring:
  data:
    mongodb:
      uri: mongodb+srv://1409nguyenduc:P4XNQNZFG0Gd2Yxm@ghidiem.zpn1q.mongodb.net/?retryWrites=true&w=majority&appName=ghidiem
      database: ghidiem
